In [9]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [10]:
import pandas as pd
import math
import numpy as np
import matplotlib.pyplot as plt

In [11]:
def cost_function(X,y,w): ###define cost function
  hypothesis = np.dot(X,w.T) ###calculation of hypothesis for all instances
  J = (1/(2*len(y))) * np.sum((hypothesis - y) ** 2) ####as mention in the class notes
  # J = (1/(2*len(y))) * np.sum((hypothesis - y) ** 2)+(lamb/2)*np.sum(w**2) ####as mention
  return J

In [12]:
def batch_gradient_descent(X,y,w,alpha,iters,lamb):
  cost_history = np.zeros(iters) # cost function for each iteration
  #initalize our cost history list to store the cost function on every iteration
  for i in range(iters):
    hypothesis = np.dot(X,w.T)
    #w = (w*(1-alpha*lamb)) -(alpha/len(y)) * np.dot(hypothesis - y, X)
    w = w - (alpha/len(y)) * np.dot(hypothesis - y, X)
    #cost_history[i] = cost_function(X,y,w,lamb)
    cost_history[i] = cost_function(X,y,w)
  return w,cost_history

In [13]:
def MB_gradient_descent(X,y,w,alpha, iters, batch_size):
  cost_history = np.zeros(iters)
  for i in range(iters):
    rand_index = np.random.randint(len(y)-batch_size)
    ind_x = X[rand_index:rand_index+batch_size]
    ind_y = y[rand_index:rand_index+batch_size]
    w = w - (alpha/batch_size) * (ind_x.T.dot(ind_x.dot(w) - ind_y))
    cost_history[i] = cost_function(ind_x,ind_y,w)
  return w, cost_history

In [14]:
def stochastic_gradient_descent(X,y,w,alpha, iters):
  cost_history = np.zeros(iters)
  for i in range(iters):
    rand_index = np.random.randint(len(y)-1)
    ind_x = X[rand_index:rand_index+1]
    ind_y = y[rand_index:rand_index+1]
    w = w - alpha * (ind_x.T.dot(ind_x.dot(w) - ind_y))
    cost_history[i] = cost_function(ind_x,ind_y,w)
  return w, cost_history

trainingData

In [15]:
dataxtr = pd.read_csv('/content/drive/MyDrive/xtr.csv',header=None)
dataytr = pd.read_csv('/content/drive/MyDrive/ytr.csv',header=None)


TestingData

In [16]:
dataxte = pd.read_csv('/content/drive/MyDrive/xte.csv',header=None)
datayte = pd.read_csv('/content/drive/MyDrive/yte.csv',header=None)


In [47]:
data_XTraining=dataxtr.values
X=data_XTraining[:,:]
# print(X)
m=X.shape[0]
xmin=np.min(X,axis=0)
xmax=np.max(X,axis=0)
# print(xmin , xmax)
X = (X- xmin)/(xmax-xmin) #Normalization
# print(X)

In [49]:
pp = np.ones([m, 1]) # vector containg ones as all elements
X = np.append(pp,X, axis=1) #Column of ones
print(X)

[[1.         0.51322751 0.0729927 ]
 [1.         0.51322751 0.74452555]
 [1.         0.51322751 0.62043796]
 [1.         0.51322751 0.        ]
 [1.         0.51322751 0.6350365 ]
 [1.         0.51322751 0.02919708]
 [1.         0.51322751 0.57664234]
 [1.         0.51322751 0.64233577]
 [1.         0.51322751 0.11678832]
 [1.         0.51322751 0.64963504]
 [1.         0.51322751 0.62043796]
 [1.         0.74603175 0.80291971]
 [1.         0.97883598 0.43065693]
 [1.         0.25396825 0.24817518]
 [1.         0.02116402 0.62773723]
 [1.         0.51322751 0.81021898]
 [1.         0.74603175 1.        ]
 [1.         0.97354497 0.44525547]
 [1.         0.02116402 0.25547445]
 [1.         0.50793651 0.64233577]
 [1.         0.73544974 0.82481752]
 [1.         0.97354497 1.        ]
 [1.         0.26984127 0.45985401]
 [1.         0.02116402 0.28467153]
 [1.         0.51322751 0.6350365 ]
 [1.         0.73015873 0.81021898]
 [1.         0.96296296 1.        ]
 [1.         0.25925926 0.45

In [50]:
X.shape

(55, 3)